spring:
  profiles:
    active: dev
  application:
    name: service-sharding
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath*:com/jzc/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080
  context-path: /sharding